#server:
 # context-path: /lease
spring:
  mvc:
   view:
    prefix: /WEB-INF/views/
    suffix: .jsp
   static-path-pattern: /**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/lease?characterEncoding=utf-8&useSSL=false&useUnicode=true
jpa:
  show-sql: true

